// Phase Five: Content Management. One generic content_items table (see
// schema.sql) covers five content types through a single CRUD UI. Four
// types (tips, templates, insights, announcements) are lists; PDF Footer
// is a singleton (there's only ever meaningfully one), so it gets a
// simpler single-item editor instead of a list.

import { renderAppShell } from '../components/appShell.js';
import { emptyStateHTML } from '../components/emptyState.js';
import { loadingStateHTML } from '../components/loadingState.js';
import { createModal } from '../components/modal.js';
import { icon } from '../components/icons.js';
import {
  listContentByType, createContentItem, updateContentItem, deleteContentItem
} from '../lib/contentApi.js';

const TYPES = [
  {
    key: 'wellness_tip', label: 'Wellness Tips', hasTitle: false, singleton: false,
    placeholder: 'e.g. "A short walk after meals can help with digestion and steadier energy."'
  },
  {
    key: 'reflection_template', label: 'Reflection Templates', hasTitle: true, singleton: false,
    placeholder: 'A reusable paragraph pattern for the Body Reflection section...'
  },
  {
    key: 'insight', label: 'Health Insights', hasTitle: true, singleton: false,
    placeholder: 'A short educational insight shown to users...'
  },
  {
    key: 'announcement', label: 'Announcements', hasTitle: false, singleton: false,
    placeholder: 'A banner message shown at the top of the app, e.g. "New: dark mode is here."'
  },
  {
    key: 'pdf_footer', label: 'PDF Footer', hasTitle: false, singleton: true,
    placeholder: 'Generated by Body IQ'
  }
];

function escapeHtml(str) {
  const div = document.createElement('div');
  div.textContent = str == null ? '' : String(str);
  return div.innerHTML;
}

function truncate(str, len) {
  if (!str) return '';
  return str.length > len ? str.slice(0, len).trim() + '\u2026' : str;
}

function statusBadge(status) {
  const cls = status === 'published' ? 'badge-published' : status === 'disabled' ? 'badge-disabled' : 'badge-draft';
  return '<span class="status-badge ' + cls + '">' + escapeHtml(status) + '</span>';
}

export async function renderContent(container) {
  const main = await renderAppShell(container, { title: 'Content' });
  if (!main) return;

  let activeType = TYPES[0].key;

  main.innerHTML = `
    <div class="content-tabs" id="content-tabs">
      ${TYPES.map(function (t, i) {
        return '<button type="button" class="content-tab' + (i === 0 ? ' active' : '') + '" data-type="' + t.key + '">' + escapeHtml(t.label) + '</button>';
      }).join('')}
    </div>
    <div class="content-tab-header">
      <button type="button" class="btn-primary" id="new-content-btn">+ New</button>
    </div>
    <div id="content-list-wrap"></div>
  `;

  function currentTypeConfig() {
    return TYPES.find(function (t) { return t.key === activeType; });
  }

  function contentRowHTML(item, typeConfig) {
    const titleLine = typeConfig.hasTitle && item.title ? escapeHtml(item.title) : truncate(item.body, 60);
    const toggleLabel = item.status === 'published' ? 'Disable' : 'Publish';
    return `
      <div class="content-row">
        <div class="content-row-main">
          <div class="content-row-title">${titleLine}</div>
          <div class="content-row-body">${escapeHtml(truncate(item.body, 110))}</div>
        </div>
        <div class="content-row-meta">${statusBadge(item.status)}</div>
        <div class="content-row-actions">
          <button type="button" class="btn-secondary" data-edit-id="${item.id}">Edit</button>
          <button type="button" class="btn-secondary" data-toggle-id="${item.id}">${toggleLabel}</button>
          <button type="button" class="btn-danger" data-delete-id="${item.id}" aria-label="Delete">${icon('close', 15)}</button>
        </div>
      </div>
    `;
  }

  async function renderActiveTab() {
    const typeConfig = currentTypeConfig();
    const listWrap = main.querySelector('#content-list-wrap');
    listWrap.innerHTML = loadingStateHTML('Loading\u2026');

    let items;
    try {
      items = await listContentByType(activeType);
    } catch (err) {
      listWrap.innerHTML = '<div class="content-empty-wrap">' +
        emptyStateHTML({ iconName: 'content', title: "Couldn't load content", message: err.message }) +
        '</div>';
      return;
    }

    if (typeConfig.singleton) {
      renderSingletonTab(listWrap, typeConfig, items[0] || null);
      return;
    }

    if (!items.length) {
      listWrap.innerHTML = '<div class="content-empty-wrap">' +
        emptyStateHTML({
          iconName: 'content',
          title: 'Nothing here yet',
          message: 'Create your first item to get started \u2014 use the "+ New" button above.'
        }) + '</div>';
      return;
    }

    listWrap.innerHTML = '<div class="content-table">' +
      items.map(function (item) { return contentRowHTML(item, typeConfig); }).join('') +
      '</div>';

    listWrap.querySelectorAll('[data-edit-id]').forEach(function (btn) {
      btn.addEventListener('click', function () {
        const item = items.find(function (i) { return i.id === btn.getAttribute('data-edit-id'); });
        openEditor(typeConfig, item);
      });
    });
    listWrap.querySelectorAll('[data-toggle-id]').forEach(function (btn) {
      btn.addEventListener('click', async function () {
        const item = items.find(function (i) { return i.id === btn.getAttribute('data-toggle-id'); });
        const nextStatus = item.status === 'published' ? 'disabled' : 'published';
        btn.disabled = true;
        try {
          await updateContentItem(item.id, { status: nextStatus });
          renderActiveTab();
        } catch (err) {
          alert('Could not update status: ' + err.message);
          btn.disabled = false;
        }
      });
    });
    listWrap.querySelectorAll('[data-delete-id]').forEach(function (btn) {
      btn.addEventListener('click', async function () {
        if (!confirm('Delete this item? This cannot be undone.')) return;
        btn.disabled = true;
        try {
          await deleteContentItem(btn.getAttribute('data-delete-id'));
          renderActiveTab();
        } catch (err) {
          alert('Could not delete: ' + err.message);
          btn.disabled = false;
        }
      });
    });
  }

  function renderSingletonTab(wrap, typeConfig, item) {
    const currentText = item ? escapeHtml(item.body) : escapeHtml(typeConfig.placeholder) + ' <span class="content-singleton-default-tag">(default \u2014 nothing set yet)</span>';
    wrap.innerHTML = `
      <div class="content-singleton-card">
        <h3 class="content-singleton-title">${typeConfig.label}</h3>
        <p class="content-singleton-current">${currentText}</p>
        <button type="button" class="btn-primary" id="edit-singleton-btn">${item ? 'Edit' : 'Set custom footer'}</button>
      </div>
    `;
    wrap.querySelector('#edit-singleton-btn').addEventListener('click', function () {
      openEditor(typeConfig, item);
    });
  }

  function openEditor(typeConfig, existingItem) {
    const isEdit = !!existingItem;
    const bodyHTML = `
      <form id="content-form" class="content-form">
        ${typeConfig.hasTitle ? `
          <label>Title
            <input type="text" name="title" value="${existingItem ? escapeHtml(existingItem.title || '') : ''}" />
          </label>
        ` : ''}
        <label>${typeConfig.singleton ? 'Footer text' : 'Content'}
          <textarea name="body" rows="5" placeholder="${escapeHtml(typeConfig.placeholder)}" required>${existingItem ? escapeHtml(existingItem.body) : ''}</textarea>
        </label>
        ${!typeConfig.singleton ? `
          <label>Status
            <select name="status">
              <option value="draft" ${existingItem && existingItem.status === 'draft' ? 'selected' : ''}>Draft</option>
              <option value="published" ${!existingItem || existingItem.status === 'published' ? 'selected' : ''}>Published</option>
              <option value="disabled" ${existingItem && existingItem.status === 'disabled' ? 'selected' : ''}>Disabled</option>
            </select>
          </label>
        ` : ''}
        <p class="form-error" id="content-form-error" hidden></p>
        <div class="modal-actions">
          <button type="button" class="btn-secondary" id="content-form-cancel">Cancel</button>
          <button type="submit" class="btn-primary" id="content-form-submit">${isEdit ? 'Save changes' : 'Create'}</button>
        </div>
      </form>
    `;

    createModal({
      title: (isEdit ? 'Edit ' : 'New ') + typeConfig.label.replace(/s$/, ''),
      bodyHTML: bodyHTML,
      onMount: function (modalEl, close) {
        const form = modalEl.querySelector('#content-form');
        const errorEl = modalEl.querySelector('#content-form-error');
        modalEl.querySelector('#content-form-cancel').addEventListener('click', close);

        form.addEventListener('submit', async function (e) {
          e.preventDefault();
          errorEl.hidden = true;

          const fd = new FormData(form);
          const body = (fd.get('body') || '').trim();
          if (!body) {
            errorEl.textContent = 'Content cannot be empty.';
            errorEl.hidden = false;
            return;
          }

          const payload = { type: typeConfig.key, body: body };
          if (typeConfig.hasTitle) payload.title = (fd.get('title') || '').trim();
          payload.status = typeConfig.singleton ? 'published' : fd.get('status');

          const submitBtn = modalEl.querySelector('#content-form-submit');
          submitBtn.disabled = true;
          submitBtn.textContent = 'Saving\u2026';

          try {
            if (isEdit) {
              await updateContentItem(existingItem.id, payload);
            } else {
              await createContentItem(payload);
            }
            close();
            renderActiveTab();
          } catch (err) {
            errorEl.textContent = err.message;
            errorEl.hidden = false;
            submitBtn.disabled = false;
            submitBtn.textContent = isEdit ? 'Save changes' : 'Create';
          }
        });
      }
    });
  }

  main.querySelectorAll('.content-tab').forEach(function (tab) {
    tab.addEventListener('click', function () {
      main.querySelectorAll('.content-tab').forEach(function (t) { t.classList.remove('active'); });
      tab.classList.add('active');
      activeType = tab.getAttribute('data-type');
      main.querySelector('#new-content-btn').style.display = currentTypeConfig().singleton ? 'none' : 'inline-flex';
      renderActiveTab();
    });
  });

  main.querySelector('#new-content-btn').addEventListener('click', function () {
    openEditor(currentTypeConfig(), null);
  });

  renderActiveTab();
}
