// Runs as the Netlify build command. Reads SUPABASE_URL and SUPABASE_ANON_KEY
// from the environment (set in Netlify's dashboard, never committed) and
// writes them into src/config.js, which is gitignored.
//
// This keeps real credentials out of version control entirely, while still
// letting the frontend import them like any other module.

const fs = require('fs');
const path = require('path');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error(
    'Missing SUPABASE_URL or SUPABASE_ANON_KEY environment variables. ' +
    'Set these in Netlify under Site settings -> Environment variables, ' +
    'or in a local .env file for local builds.'
  );
  process.exit(1);
}

const output = `// AUTO-GENERATED by scripts/generate-config.js at build time.
// Do not edit this file directly and do not commit real values.
export const SUPABASE_URL = ${JSON.stringify(SUPABASE_URL)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(SUPABASE_ANON_KEY)};
export const BUILT_AT = ${JSON.stringify(new Date().toISOString())};
`;

const outPath = path.join(__dirname, '..', 'src', 'config.js');
fs.writeFileSync(outPath, output, 'utf8');
console.log('Wrote', outPath);
