// PLACEHOLDER FILE — normally auto-generated by scripts/generate-config.js
// during the Netlify build from real SUPABASE_URL / SUPABASE_ANON_KEY
// environment variables. This file is listed in .gitignore.
//
// Replace the values below with your real Supabase project URL and anon
// key for local testing, or just run `npm run build` locally with a .env
// file present to regenerate this file automatically.

export const SUPABASE_URL = 'https://stebrrcpglrjdvalubxj.supabase.co/rest/v1/';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0ZWJycmNwZ2xyamR2YWx1YnhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0MTU2OTgsImV4cCI6MjEwMDk5MTY5OH0.YrdFFOH3P9WdW-qh9a6DFvi9k8rqnhpcHcOK35Cwd-4';
export const BUILT_AT = null; // real builds get an actual ISO timestamp here
